name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen 1.16.1
        run: |
          wget https://www.doxygen.nl/files/doxygen-1.16.1.linux.bin.tar.gz
          tar -xzf doxygen-1.16.1.linux.bin.tar.gz
          sudo cp doxygen-1.16.1/bin/doxygen /usr/local/bin/

      - name: Build documentation
        working-directory: ./Docs
        run: doxygen doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Docs/html
          publish_branch: gh-pages
